### ISSUE TITLE
Initial Draft re-design [The Fede Edition]

### ISSUE THREAD

**Issue by schilkp** [schilkp/reginald#1]
0) Split input and data model

1) Add "Register Block" system:
```yaml
   CH1_SET: # Single register block instantiation
     start_adr: 0x01
     register_block_template: "CH_SETTINGS"

   CHn_SET: # Multiple register block instantiation
      start_adr: {1: 0x100, B: 0x200}
      replace_str_with_instance_name: "n" # Optional, Fallback: suffix w\o any padding char
      register_block_template: "CH_SETTINGS"
```
2) Move from set width to per-register with default:
```yaml
default_register_bitwidth: 8

...
registers:
  REGA:
    bitwidth: 8 # Override
```

3) Enum: 
     Refactor 'enums' to allow for brief+doc, and make syntax identical to field enum:
```yaml
register:
  A:
    ...
    fields:
       SETTINGS:
         bits: []
         brief:
         doc:
          enum: 
            VALA:
              ..
       OTHERFIELD:
         ...
         enum: GPIO_MODE
       

shared_enums:
  GPIO_MODE:
    brief:
    doc:
    enum:
      OUTPUT:
        value: 0
        brief: Pin configured as output.
      INPUT:
        value: 1
        brief: Pin configured as input.
```

4) Device Name -> Map name
```yaml
map_name: ADS129x
```
5) Field bit definitions:

```yaml
# Add:
    bits: 1 # == [1]
    bits: 1-4 # == [1,2,3,4]
    bits: [1, 4-10] # == [1,4,5,6,7,8,9,10]

# Remove: 
    bits:
      lsb_position: 1
      width: 3
```

6) Access:
```yaml
    access: [r, w]
```
