### ISSUE TITLE
Add register_field_templates 

### ISSUE THREAD

**Issue by villanif** [schilkp/reginald#16]
add nex register_field_templates feature, to quickly reproduce register fields. structure can be similar to already existing register_block_template: 
```
register_field_templates:
  EXAMPLE_FIELD_n:
    bit_size: 3
    enum:
      SOMETHING:
        ...
      SOMETHINGELSE:
        ...
```
