### ISSUE TITLE
c.funcpack: Validate function with unused args

### ISSUE THREAD

**Issue by schilkp** [schilkp/reginald#42]
Since not all fields with content require validation, some registers produce validate funcs with unused args:

```yaml
name: TEST
defaults:
  layout_bitwidth: 8

registers:
  XTAL_GOOD: !Register
    adr: 0x77
    reset_val: 0x00
    doc: Reads as true if the clock source is stable.
    layout: !Layout
      DATA:
        bits: 0
        access: [R]
        accepts: !Bool
```

```c
/**
 * @brief Validate struct
 * @returns 0 if valid.
 * @returns the position of the first invalid field if invalid.
 * Confirms that all enums are valid, and all values fit into respective fields
 */
static inline int test_validate_xtal_good(const struct test_xtal_good *r) {
  return 0;
}
```
